# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Aeropuerto_pb2 as Aeropuerto__pb2


class PruebaStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.enviar_altura = channel.unary_unary(
        '/Aeropuerto.Prueba/enviar_altura',
        request_serializer=Aeropuerto__pb2.mensaje.SerializeToString,
        response_deserializer=Aeropuerto__pb2.respuesta.FromString,
        )


class PruebaServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def enviar_altura(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PruebaServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'enviar_altura': grpc.unary_unary_rpc_method_handler(
          servicer.enviar_altura,
          request_deserializer=Aeropuerto__pb2.mensaje.FromString,
          response_serializer=Aeropuerto__pb2.respuesta.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Aeropuerto.Prueba', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
