// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Torre.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Aeropuerto {

  /// <summary>Holder for reflection information generated from Torre.proto</summary>
  public static partial class TorreReflection {

    #region Descriptor
    /// <summary>File descriptor for Torre.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TorreReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtUb3JyZS5wcm90bxIKQWVyb3B1ZXJ0byIzCglQaXN0YV9EZXMSEAoISWRf",
            "YXZpb24YASABKAkSFAoMTmFtZV9kZXN0aW5vGAIgASgJIrYBCghSZXNwX0Rl",
            "cxIdChVBdXRvcml6YWNpb25fZGVzcGVndWUYASABKAgSFgoOUGlzdGFfZGVz",
            "cGVndWUYAiABKAkSFwoPQWx0dXJhX2Rlc3BlZ3VlGAMgASgFEhkKEVBvc2lj",
            "aW9uX2Rlc3BlZ3VlGAQgASgFEhkKEUFudGVyaW9yX2Rlc3BlZ3VlGAUgASgJ",
            "EhIKCklwX2Rlc3Rpbm8YBiABKAkSEAoISWRfYXZpb24YByABKAkiYQoIQ29u",
            "c19EZXMSEAoISWRfYXZpb24YASABKAkSFAoMTmFtZV9kZXN0aW5vGAIgASgJ",
            "EhQKDFBpc3RhX2VzcGVyYRgDIAEoCRIXCg9Qb3NpY2lvbl9lc3BlcmEYBCAB",
            "KAUitwEKCVJlc3BfQ29ucxIdChVBdXRvcml6YWNpb25fZGVzcGVndWUYASAB",
            "KAgSFgoOUGlzdGFfZGVzcGVndWUYAiABKAkSFwoPQWx0dXJhX2Rlc3BlZ3Vl",
            "GAMgASgFEhkKEVBvc2ljaW9uX2Rlc3BlZ3VlGAQgASgFEhkKEUFudGVyaW9y",
            "X2Rlc3BlZ3VlGAUgASgJEhIKCklwX2Rlc3Rpbm8YBiABKAkSEAoISWRfYXZp",
            "b24YByABKAkiHAoIUGlzdGFfQXQSEAoISWRfYXZpb24YASABKAkiqwEKB1Jl",
            "c3BfQXQSHwoXQXV0b3JpemFjaW9uX2F0ZXJyaXphamUYASABKAgSGAoQUGlz",
            "dGFfYXRlcnJpemFqZRgCIAEoBRIZChFBbHR1cmFfYXRlcnJpemFqZRgDIAEo",
            "BRIbChNQb3NpY2lvbl9hdGVycml6YWplGAQgASgFEhsKE0FudGVyaW9yX2F0",
            "ZXJyaXphamUYBSABKAkSEAoISWRfYXZpb24YBiABKAkiJgoLSWRfUGFudGFs",
            "bGESFwoPTm9tYnJlX1BhbnRhbGxhGAEgASgJItUCCg1SZXNwX1BhbnRhbGxh",
            "Eg8KB1NhbGlkYTEYASABKAkSEAoIQV9Eb25kZTEYAiABKAkSFQoNUGlzdGFf",
            "U2FsaWRhMRgDIAEoCRIUCgxIb3JhX1NhbGlkYTEYBCABKAkSDwoHU2FsaWRh",
            "MhgFIAEoCRIQCghBX0RvbmRlMhgGIAEoCRIVCg1QaXN0YV9TYWxpZGEyGAcg",
            "ASgJEhQKDEhvcmFfU2FsaWRhMhgIIAEoCRIPCgdMbGVnZGExGAkgASgJEhEK",
            "CURlX2RvbmRlMRgKIAEoCRIWCg5QaXN0YV9MbGVnYWRhMRgLIAEoCRIVCg1I",
            "b3JhX0xsZWdhZGExGAwgASgJEg8KB0xsZWdkYTIYDSABKAkSEQoJRGVfZG9u",
            "ZGUyGA4gASgJEhYKDlBpc3RhX0xsZWdhZGEyGA8gASgJEhUKDUhvcmFfTGxl",
            "Z2FkYTIYECABKAkynwIKD1NlcnZfQWVyb3B1ZXJ0bxJACg9lbnZpYXJfZGVz",
            "cGVndWUSFS5BZXJvcHVlcnRvLlBpc3RhX0RlcxoULkFlcm9wdWVydG8uUmVz",
            "cF9EZXMiABJDChJjb25maXJtYXJfZGVzcGVndWUSFC5BZXJvcHVlcnRvLkNv",
            "bnNfRGVzGhUuQWVyb3B1ZXJ0by5SZXNwX0NvbnMiABJAChFlbnZpYXJfYXRl",
            "cnJpemFqZRIULkFlcm9wdWVydG8uUGlzdGFfQXQaEy5BZXJvcHVlcnRvLlJl",
            "c3BfQXQiABJDCgtlbnZpYXJfaW5mbxIXLkFlcm9wdWVydG8uSWRfUGFudGFs",
            "bGEaGS5BZXJvcHVlcnRvLlJlc3BfUGFudGFsbGEiAEI2Chtpby5ncnBjLmV4",
            "YW1wbGVzLkFlcm9wdWVydG9CD0Flcm9wdWVydG9Qcm90b1ABogIDSExXYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Aeropuerto.Pista_Des), global::Aeropuerto.Pista_Des.Parser, new[]{ "IdAvion", "NameDestino" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Aeropuerto.Resp_Des), global::Aeropuerto.Resp_Des.Parser, new[]{ "AutorizacionDespegue", "PistaDespegue", "AlturaDespegue", "PosicionDespegue", "AnteriorDespegue", "IpDestino", "IdAvion" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Aeropuerto.Cons_Des), global::Aeropuerto.Cons_Des.Parser, new[]{ "IdAvion", "NameDestino", "PistaEspera", "PosicionEspera" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Aeropuerto.Resp_Cons), global::Aeropuerto.Resp_Cons.Parser, new[]{ "AutorizacionDespegue", "PistaDespegue", "AlturaDespegue", "PosicionDespegue", "AnteriorDespegue", "IpDestino", "IdAvion" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Aeropuerto.Pista_At), global::Aeropuerto.Pista_At.Parser, new[]{ "IdAvion" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Aeropuerto.Resp_At), global::Aeropuerto.Resp_At.Parser, new[]{ "AutorizacionAterrizaje", "PistaAterrizaje", "AlturaAterrizaje", "PosicionAterrizaje", "AnteriorAterrizaje", "IdAvion" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Aeropuerto.Id_Pantalla), global::Aeropuerto.Id_Pantalla.Parser, new[]{ "NombrePantalla" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Aeropuerto.Resp_Pantalla), global::Aeropuerto.Resp_Pantalla.Parser, new[]{ "Salida1", "ADonde1", "PistaSalida1", "HoraSalida1", "Salida2", "ADonde2", "PistaSalida2", "HoraSalida2", "Llegda1", "DeDonde1", "PistaLlegada1", "HoraLlegada1", "Llegda2", "DeDonde2", "PistaLlegada2", "HoraLlegada2" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Pista_Des : pb::IMessage<Pista_Des> {
    private static readonly pb::MessageParser<Pista_Des> _parser = new pb::MessageParser<Pista_Des>(() => new Pista_Des());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Pista_Des> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Aeropuerto.TorreReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Pista_Des() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Pista_Des(Pista_Des other) : this() {
      idAvion_ = other.idAvion_;
      nameDestino_ = other.nameDestino_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Pista_Des Clone() {
      return new Pista_Des(this);
    }

    /// <summary>Field number for the "Id_avion" field.</summary>
    public const int IdAvionFieldNumber = 1;
    private string idAvion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IdAvion {
      get { return idAvion_; }
      set {
        idAvion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Name_destino" field.</summary>
    public const int NameDestinoFieldNumber = 2;
    private string nameDestino_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NameDestino {
      get { return nameDestino_; }
      set {
        nameDestino_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Pista_Des);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Pista_Des other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IdAvion != other.IdAvion) return false;
      if (NameDestino != other.NameDestino) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (IdAvion.Length != 0) hash ^= IdAvion.GetHashCode();
      if (NameDestino.Length != 0) hash ^= NameDestino.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (IdAvion.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IdAvion);
      }
      if (NameDestino.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NameDestino);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (IdAvion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdAvion);
      }
      if (NameDestino.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NameDestino);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Pista_Des other) {
      if (other == null) {
        return;
      }
      if (other.IdAvion.Length != 0) {
        IdAvion = other.IdAvion;
      }
      if (other.NameDestino.Length != 0) {
        NameDestino = other.NameDestino;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            IdAvion = input.ReadString();
            break;
          }
          case 18: {
            NameDestino = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Resp_Des : pb::IMessage<Resp_Des> {
    private static readonly pb::MessageParser<Resp_Des> _parser = new pb::MessageParser<Resp_Des>(() => new Resp_Des());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Resp_Des> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Aeropuerto.TorreReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resp_Des() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resp_Des(Resp_Des other) : this() {
      autorizacionDespegue_ = other.autorizacionDespegue_;
      pistaDespegue_ = other.pistaDespegue_;
      alturaDespegue_ = other.alturaDespegue_;
      posicionDespegue_ = other.posicionDespegue_;
      anteriorDespegue_ = other.anteriorDespegue_;
      ipDestino_ = other.ipDestino_;
      idAvion_ = other.idAvion_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resp_Des Clone() {
      return new Resp_Des(this);
    }

    /// <summary>Field number for the "Autorizacion_despegue" field.</summary>
    public const int AutorizacionDespegueFieldNumber = 1;
    private bool autorizacionDespegue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool AutorizacionDespegue {
      get { return autorizacionDespegue_; }
      set {
        autorizacionDespegue_ = value;
      }
    }

    /// <summary>Field number for the "Pista_despegue" field.</summary>
    public const int PistaDespegueFieldNumber = 2;
    private string pistaDespegue_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PistaDespegue {
      get { return pistaDespegue_; }
      set {
        pistaDespegue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Altura_despegue" field.</summary>
    public const int AlturaDespegueFieldNumber = 3;
    private int alturaDespegue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int AlturaDespegue {
      get { return alturaDespegue_; }
      set {
        alturaDespegue_ = value;
      }
    }

    /// <summary>Field number for the "Posicion_despegue" field.</summary>
    public const int PosicionDespegueFieldNumber = 4;
    private int posicionDespegue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PosicionDespegue {
      get { return posicionDespegue_; }
      set {
        posicionDespegue_ = value;
      }
    }

    /// <summary>Field number for the "Anterior_despegue" field.</summary>
    public const int AnteriorDespegueFieldNumber = 5;
    private string anteriorDespegue_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AnteriorDespegue {
      get { return anteriorDespegue_; }
      set {
        anteriorDespegue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Ip_destino" field.</summary>
    public const int IpDestinoFieldNumber = 6;
    private string ipDestino_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IpDestino {
      get { return ipDestino_; }
      set {
        ipDestino_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Id_avion" field.</summary>
    public const int IdAvionFieldNumber = 7;
    private string idAvion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IdAvion {
      get { return idAvion_; }
      set {
        idAvion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Resp_Des);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Resp_Des other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AutorizacionDespegue != other.AutorizacionDespegue) return false;
      if (PistaDespegue != other.PistaDespegue) return false;
      if (AlturaDespegue != other.AlturaDespegue) return false;
      if (PosicionDespegue != other.PosicionDespegue) return false;
      if (AnteriorDespegue != other.AnteriorDespegue) return false;
      if (IpDestino != other.IpDestino) return false;
      if (IdAvion != other.IdAvion) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (AutorizacionDespegue != false) hash ^= AutorizacionDespegue.GetHashCode();
      if (PistaDespegue.Length != 0) hash ^= PistaDespegue.GetHashCode();
      if (AlturaDespegue != 0) hash ^= AlturaDespegue.GetHashCode();
      if (PosicionDespegue != 0) hash ^= PosicionDespegue.GetHashCode();
      if (AnteriorDespegue.Length != 0) hash ^= AnteriorDespegue.GetHashCode();
      if (IpDestino.Length != 0) hash ^= IpDestino.GetHashCode();
      if (IdAvion.Length != 0) hash ^= IdAvion.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (AutorizacionDespegue != false) {
        output.WriteRawTag(8);
        output.WriteBool(AutorizacionDespegue);
      }
      if (PistaDespegue.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PistaDespegue);
      }
      if (AlturaDespegue != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(AlturaDespegue);
      }
      if (PosicionDespegue != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(PosicionDespegue);
      }
      if (AnteriorDespegue.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(AnteriorDespegue);
      }
      if (IpDestino.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(IpDestino);
      }
      if (IdAvion.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(IdAvion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (AutorizacionDespegue != false) {
        size += 1 + 1;
      }
      if (PistaDespegue.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PistaDespegue);
      }
      if (AlturaDespegue != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AlturaDespegue);
      }
      if (PosicionDespegue != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PosicionDespegue);
      }
      if (AnteriorDespegue.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AnteriorDespegue);
      }
      if (IpDestino.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IpDestino);
      }
      if (IdAvion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdAvion);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Resp_Des other) {
      if (other == null) {
        return;
      }
      if (other.AutorizacionDespegue != false) {
        AutorizacionDespegue = other.AutorizacionDespegue;
      }
      if (other.PistaDespegue.Length != 0) {
        PistaDespegue = other.PistaDespegue;
      }
      if (other.AlturaDespegue != 0) {
        AlturaDespegue = other.AlturaDespegue;
      }
      if (other.PosicionDespegue != 0) {
        PosicionDespegue = other.PosicionDespegue;
      }
      if (other.AnteriorDespegue.Length != 0) {
        AnteriorDespegue = other.AnteriorDespegue;
      }
      if (other.IpDestino.Length != 0) {
        IpDestino = other.IpDestino;
      }
      if (other.IdAvion.Length != 0) {
        IdAvion = other.IdAvion;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AutorizacionDespegue = input.ReadBool();
            break;
          }
          case 18: {
            PistaDespegue = input.ReadString();
            break;
          }
          case 24: {
            AlturaDespegue = input.ReadInt32();
            break;
          }
          case 32: {
            PosicionDespegue = input.ReadInt32();
            break;
          }
          case 42: {
            AnteriorDespegue = input.ReadString();
            break;
          }
          case 50: {
            IpDestino = input.ReadString();
            break;
          }
          case 58: {
            IdAvion = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Cons_Des : pb::IMessage<Cons_Des> {
    private static readonly pb::MessageParser<Cons_Des> _parser = new pb::MessageParser<Cons_Des>(() => new Cons_Des());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Cons_Des> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Aeropuerto.TorreReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Cons_Des() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Cons_Des(Cons_Des other) : this() {
      idAvion_ = other.idAvion_;
      nameDestino_ = other.nameDestino_;
      pistaEspera_ = other.pistaEspera_;
      posicionEspera_ = other.posicionEspera_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Cons_Des Clone() {
      return new Cons_Des(this);
    }

    /// <summary>Field number for the "Id_avion" field.</summary>
    public const int IdAvionFieldNumber = 1;
    private string idAvion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IdAvion {
      get { return idAvion_; }
      set {
        idAvion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Name_destino" field.</summary>
    public const int NameDestinoFieldNumber = 2;
    private string nameDestino_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NameDestino {
      get { return nameDestino_; }
      set {
        nameDestino_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Pista_espera" field.</summary>
    public const int PistaEsperaFieldNumber = 3;
    private string pistaEspera_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PistaEspera {
      get { return pistaEspera_; }
      set {
        pistaEspera_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Posicion_espera" field.</summary>
    public const int PosicionEsperaFieldNumber = 4;
    private int posicionEspera_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PosicionEspera {
      get { return posicionEspera_; }
      set {
        posicionEspera_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Cons_Des);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Cons_Des other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IdAvion != other.IdAvion) return false;
      if (NameDestino != other.NameDestino) return false;
      if (PistaEspera != other.PistaEspera) return false;
      if (PosicionEspera != other.PosicionEspera) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (IdAvion.Length != 0) hash ^= IdAvion.GetHashCode();
      if (NameDestino.Length != 0) hash ^= NameDestino.GetHashCode();
      if (PistaEspera.Length != 0) hash ^= PistaEspera.GetHashCode();
      if (PosicionEspera != 0) hash ^= PosicionEspera.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (IdAvion.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IdAvion);
      }
      if (NameDestino.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NameDestino);
      }
      if (PistaEspera.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PistaEspera);
      }
      if (PosicionEspera != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(PosicionEspera);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (IdAvion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdAvion);
      }
      if (NameDestino.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NameDestino);
      }
      if (PistaEspera.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PistaEspera);
      }
      if (PosicionEspera != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PosicionEspera);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Cons_Des other) {
      if (other == null) {
        return;
      }
      if (other.IdAvion.Length != 0) {
        IdAvion = other.IdAvion;
      }
      if (other.NameDestino.Length != 0) {
        NameDestino = other.NameDestino;
      }
      if (other.PistaEspera.Length != 0) {
        PistaEspera = other.PistaEspera;
      }
      if (other.PosicionEspera != 0) {
        PosicionEspera = other.PosicionEspera;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            IdAvion = input.ReadString();
            break;
          }
          case 18: {
            NameDestino = input.ReadString();
            break;
          }
          case 26: {
            PistaEspera = input.ReadString();
            break;
          }
          case 32: {
            PosicionEspera = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Resp_Cons : pb::IMessage<Resp_Cons> {
    private static readonly pb::MessageParser<Resp_Cons> _parser = new pb::MessageParser<Resp_Cons>(() => new Resp_Cons());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Resp_Cons> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Aeropuerto.TorreReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resp_Cons() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resp_Cons(Resp_Cons other) : this() {
      autorizacionDespegue_ = other.autorizacionDespegue_;
      pistaDespegue_ = other.pistaDespegue_;
      alturaDespegue_ = other.alturaDespegue_;
      posicionDespegue_ = other.posicionDespegue_;
      anteriorDespegue_ = other.anteriorDespegue_;
      ipDestino_ = other.ipDestino_;
      idAvion_ = other.idAvion_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resp_Cons Clone() {
      return new Resp_Cons(this);
    }

    /// <summary>Field number for the "Autorizacion_despegue" field.</summary>
    public const int AutorizacionDespegueFieldNumber = 1;
    private bool autorizacionDespegue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool AutorizacionDespegue {
      get { return autorizacionDespegue_; }
      set {
        autorizacionDespegue_ = value;
      }
    }

    /// <summary>Field number for the "Pista_despegue" field.</summary>
    public const int PistaDespegueFieldNumber = 2;
    private string pistaDespegue_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PistaDespegue {
      get { return pistaDespegue_; }
      set {
        pistaDespegue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Altura_despegue" field.</summary>
    public const int AlturaDespegueFieldNumber = 3;
    private int alturaDespegue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int AlturaDespegue {
      get { return alturaDespegue_; }
      set {
        alturaDespegue_ = value;
      }
    }

    /// <summary>Field number for the "Posicion_despegue" field.</summary>
    public const int PosicionDespegueFieldNumber = 4;
    private int posicionDespegue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PosicionDespegue {
      get { return posicionDespegue_; }
      set {
        posicionDespegue_ = value;
      }
    }

    /// <summary>Field number for the "Anterior_despegue" field.</summary>
    public const int AnteriorDespegueFieldNumber = 5;
    private string anteriorDespegue_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AnteriorDespegue {
      get { return anteriorDespegue_; }
      set {
        anteriorDespegue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Ip_destino" field.</summary>
    public const int IpDestinoFieldNumber = 6;
    private string ipDestino_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IpDestino {
      get { return ipDestino_; }
      set {
        ipDestino_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Id_avion" field.</summary>
    public const int IdAvionFieldNumber = 7;
    private string idAvion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IdAvion {
      get { return idAvion_; }
      set {
        idAvion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Resp_Cons);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Resp_Cons other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AutorizacionDespegue != other.AutorizacionDespegue) return false;
      if (PistaDespegue != other.PistaDespegue) return false;
      if (AlturaDespegue != other.AlturaDespegue) return false;
      if (PosicionDespegue != other.PosicionDespegue) return false;
      if (AnteriorDespegue != other.AnteriorDespegue) return false;
      if (IpDestino != other.IpDestino) return false;
      if (IdAvion != other.IdAvion) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (AutorizacionDespegue != false) hash ^= AutorizacionDespegue.GetHashCode();
      if (PistaDespegue.Length != 0) hash ^= PistaDespegue.GetHashCode();
      if (AlturaDespegue != 0) hash ^= AlturaDespegue.GetHashCode();
      if (PosicionDespegue != 0) hash ^= PosicionDespegue.GetHashCode();
      if (AnteriorDespegue.Length != 0) hash ^= AnteriorDespegue.GetHashCode();
      if (IpDestino.Length != 0) hash ^= IpDestino.GetHashCode();
      if (IdAvion.Length != 0) hash ^= IdAvion.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (AutorizacionDespegue != false) {
        output.WriteRawTag(8);
        output.WriteBool(AutorizacionDespegue);
      }
      if (PistaDespegue.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PistaDespegue);
      }
      if (AlturaDespegue != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(AlturaDespegue);
      }
      if (PosicionDespegue != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(PosicionDespegue);
      }
      if (AnteriorDespegue.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(AnteriorDespegue);
      }
      if (IpDestino.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(IpDestino);
      }
      if (IdAvion.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(IdAvion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (AutorizacionDespegue != false) {
        size += 1 + 1;
      }
      if (PistaDespegue.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PistaDespegue);
      }
      if (AlturaDespegue != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AlturaDespegue);
      }
      if (PosicionDespegue != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PosicionDespegue);
      }
      if (AnteriorDespegue.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AnteriorDespegue);
      }
      if (IpDestino.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IpDestino);
      }
      if (IdAvion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdAvion);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Resp_Cons other) {
      if (other == null) {
        return;
      }
      if (other.AutorizacionDespegue != false) {
        AutorizacionDespegue = other.AutorizacionDespegue;
      }
      if (other.PistaDespegue.Length != 0) {
        PistaDespegue = other.PistaDespegue;
      }
      if (other.AlturaDespegue != 0) {
        AlturaDespegue = other.AlturaDespegue;
      }
      if (other.PosicionDespegue != 0) {
        PosicionDespegue = other.PosicionDespegue;
      }
      if (other.AnteriorDespegue.Length != 0) {
        AnteriorDespegue = other.AnteriorDespegue;
      }
      if (other.IpDestino.Length != 0) {
        IpDestino = other.IpDestino;
      }
      if (other.IdAvion.Length != 0) {
        IdAvion = other.IdAvion;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AutorizacionDespegue = input.ReadBool();
            break;
          }
          case 18: {
            PistaDespegue = input.ReadString();
            break;
          }
          case 24: {
            AlturaDespegue = input.ReadInt32();
            break;
          }
          case 32: {
            PosicionDespegue = input.ReadInt32();
            break;
          }
          case 42: {
            AnteriorDespegue = input.ReadString();
            break;
          }
          case 50: {
            IpDestino = input.ReadString();
            break;
          }
          case 58: {
            IdAvion = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Pista_At : pb::IMessage<Pista_At> {
    private static readonly pb::MessageParser<Pista_At> _parser = new pb::MessageParser<Pista_At>(() => new Pista_At());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Pista_At> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Aeropuerto.TorreReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Pista_At() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Pista_At(Pista_At other) : this() {
      idAvion_ = other.idAvion_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Pista_At Clone() {
      return new Pista_At(this);
    }

    /// <summary>Field number for the "Id_avion" field.</summary>
    public const int IdAvionFieldNumber = 1;
    private string idAvion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IdAvion {
      get { return idAvion_; }
      set {
        idAvion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Pista_At);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Pista_At other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IdAvion != other.IdAvion) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (IdAvion.Length != 0) hash ^= IdAvion.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (IdAvion.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IdAvion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (IdAvion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdAvion);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Pista_At other) {
      if (other == null) {
        return;
      }
      if (other.IdAvion.Length != 0) {
        IdAvion = other.IdAvion;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            IdAvion = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Resp_At : pb::IMessage<Resp_At> {
    private static readonly pb::MessageParser<Resp_At> _parser = new pb::MessageParser<Resp_At>(() => new Resp_At());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Resp_At> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Aeropuerto.TorreReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resp_At() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resp_At(Resp_At other) : this() {
      autorizacionAterrizaje_ = other.autorizacionAterrizaje_;
      pistaAterrizaje_ = other.pistaAterrizaje_;
      alturaAterrizaje_ = other.alturaAterrizaje_;
      posicionAterrizaje_ = other.posicionAterrizaje_;
      anteriorAterrizaje_ = other.anteriorAterrizaje_;
      idAvion_ = other.idAvion_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resp_At Clone() {
      return new Resp_At(this);
    }

    /// <summary>Field number for the "Autorizacion_aterrizaje" field.</summary>
    public const int AutorizacionAterrizajeFieldNumber = 1;
    private bool autorizacionAterrizaje_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool AutorizacionAterrizaje {
      get { return autorizacionAterrizaje_; }
      set {
        autorizacionAterrizaje_ = value;
      }
    }

    /// <summary>Field number for the "Pista_aterrizaje" field.</summary>
    public const int PistaAterrizajeFieldNumber = 2;
    private int pistaAterrizaje_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PistaAterrizaje {
      get { return pistaAterrizaje_; }
      set {
        pistaAterrizaje_ = value;
      }
    }

    /// <summary>Field number for the "Altura_aterrizaje" field.</summary>
    public const int AlturaAterrizajeFieldNumber = 3;
    private int alturaAterrizaje_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int AlturaAterrizaje {
      get { return alturaAterrizaje_; }
      set {
        alturaAterrizaje_ = value;
      }
    }

    /// <summary>Field number for the "Posicion_aterrizaje" field.</summary>
    public const int PosicionAterrizajeFieldNumber = 4;
    private int posicionAterrizaje_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PosicionAterrizaje {
      get { return posicionAterrizaje_; }
      set {
        posicionAterrizaje_ = value;
      }
    }

    /// <summary>Field number for the "Anterior_aterrizaje" field.</summary>
    public const int AnteriorAterrizajeFieldNumber = 5;
    private string anteriorAterrizaje_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AnteriorAterrizaje {
      get { return anteriorAterrizaje_; }
      set {
        anteriorAterrizaje_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Id_avion" field.</summary>
    public const int IdAvionFieldNumber = 6;
    private string idAvion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IdAvion {
      get { return idAvion_; }
      set {
        idAvion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Resp_At);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Resp_At other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AutorizacionAterrizaje != other.AutorizacionAterrizaje) return false;
      if (PistaAterrizaje != other.PistaAterrizaje) return false;
      if (AlturaAterrizaje != other.AlturaAterrizaje) return false;
      if (PosicionAterrizaje != other.PosicionAterrizaje) return false;
      if (AnteriorAterrizaje != other.AnteriorAterrizaje) return false;
      if (IdAvion != other.IdAvion) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (AutorizacionAterrizaje != false) hash ^= AutorizacionAterrizaje.GetHashCode();
      if (PistaAterrizaje != 0) hash ^= PistaAterrizaje.GetHashCode();
      if (AlturaAterrizaje != 0) hash ^= AlturaAterrizaje.GetHashCode();
      if (PosicionAterrizaje != 0) hash ^= PosicionAterrizaje.GetHashCode();
      if (AnteriorAterrizaje.Length != 0) hash ^= AnteriorAterrizaje.GetHashCode();
      if (IdAvion.Length != 0) hash ^= IdAvion.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (AutorizacionAterrizaje != false) {
        output.WriteRawTag(8);
        output.WriteBool(AutorizacionAterrizaje);
      }
      if (PistaAterrizaje != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(PistaAterrizaje);
      }
      if (AlturaAterrizaje != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(AlturaAterrizaje);
      }
      if (PosicionAterrizaje != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(PosicionAterrizaje);
      }
      if (AnteriorAterrizaje.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(AnteriorAterrizaje);
      }
      if (IdAvion.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(IdAvion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (AutorizacionAterrizaje != false) {
        size += 1 + 1;
      }
      if (PistaAterrizaje != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PistaAterrizaje);
      }
      if (AlturaAterrizaje != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AlturaAterrizaje);
      }
      if (PosicionAterrizaje != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PosicionAterrizaje);
      }
      if (AnteriorAterrizaje.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AnteriorAterrizaje);
      }
      if (IdAvion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdAvion);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Resp_At other) {
      if (other == null) {
        return;
      }
      if (other.AutorizacionAterrizaje != false) {
        AutorizacionAterrizaje = other.AutorizacionAterrizaje;
      }
      if (other.PistaAterrizaje != 0) {
        PistaAterrizaje = other.PistaAterrizaje;
      }
      if (other.AlturaAterrizaje != 0) {
        AlturaAterrizaje = other.AlturaAterrizaje;
      }
      if (other.PosicionAterrizaje != 0) {
        PosicionAterrizaje = other.PosicionAterrizaje;
      }
      if (other.AnteriorAterrizaje.Length != 0) {
        AnteriorAterrizaje = other.AnteriorAterrizaje;
      }
      if (other.IdAvion.Length != 0) {
        IdAvion = other.IdAvion;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AutorizacionAterrizaje = input.ReadBool();
            break;
          }
          case 16: {
            PistaAterrizaje = input.ReadInt32();
            break;
          }
          case 24: {
            AlturaAterrizaje = input.ReadInt32();
            break;
          }
          case 32: {
            PosicionAterrizaje = input.ReadInt32();
            break;
          }
          case 42: {
            AnteriorAterrizaje = input.ReadString();
            break;
          }
          case 50: {
            IdAvion = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Id_Pantalla : pb::IMessage<Id_Pantalla> {
    private static readonly pb::MessageParser<Id_Pantalla> _parser = new pb::MessageParser<Id_Pantalla>(() => new Id_Pantalla());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Id_Pantalla> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Aeropuerto.TorreReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Id_Pantalla() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Id_Pantalla(Id_Pantalla other) : this() {
      nombrePantalla_ = other.nombrePantalla_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Id_Pantalla Clone() {
      return new Id_Pantalla(this);
    }

    /// <summary>Field number for the "Nombre_Pantalla" field.</summary>
    public const int NombrePantallaFieldNumber = 1;
    private string nombrePantalla_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NombrePantalla {
      get { return nombrePantalla_; }
      set {
        nombrePantalla_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Id_Pantalla);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Id_Pantalla other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NombrePantalla != other.NombrePantalla) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (NombrePantalla.Length != 0) hash ^= NombrePantalla.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (NombrePantalla.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(NombrePantalla);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (NombrePantalla.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NombrePantalla);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Id_Pantalla other) {
      if (other == null) {
        return;
      }
      if (other.NombrePantalla.Length != 0) {
        NombrePantalla = other.NombrePantalla;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            NombrePantalla = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Resp_Pantalla : pb::IMessage<Resp_Pantalla> {
    private static readonly pb::MessageParser<Resp_Pantalla> _parser = new pb::MessageParser<Resp_Pantalla>(() => new Resp_Pantalla());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Resp_Pantalla> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Aeropuerto.TorreReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resp_Pantalla() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resp_Pantalla(Resp_Pantalla other) : this() {
      salida1_ = other.salida1_;
      aDonde1_ = other.aDonde1_;
      pistaSalida1_ = other.pistaSalida1_;
      horaSalida1_ = other.horaSalida1_;
      salida2_ = other.salida2_;
      aDonde2_ = other.aDonde2_;
      pistaSalida2_ = other.pistaSalida2_;
      horaSalida2_ = other.horaSalida2_;
      llegda1_ = other.llegda1_;
      deDonde1_ = other.deDonde1_;
      pistaLlegada1_ = other.pistaLlegada1_;
      horaLlegada1_ = other.horaLlegada1_;
      llegda2_ = other.llegda2_;
      deDonde2_ = other.deDonde2_;
      pistaLlegada2_ = other.pistaLlegada2_;
      horaLlegada2_ = other.horaLlegada2_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resp_Pantalla Clone() {
      return new Resp_Pantalla(this);
    }

    /// <summary>Field number for the "Salida1" field.</summary>
    public const int Salida1FieldNumber = 1;
    private string salida1_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Salida1 {
      get { return salida1_; }
      set {
        salida1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "A_Donde1" field.</summary>
    public const int ADonde1FieldNumber = 2;
    private string aDonde1_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ADonde1 {
      get { return aDonde1_; }
      set {
        aDonde1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Pista_Salida1" field.</summary>
    public const int PistaSalida1FieldNumber = 3;
    private string pistaSalida1_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PistaSalida1 {
      get { return pistaSalida1_; }
      set {
        pistaSalida1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Hora_Salida1" field.</summary>
    public const int HoraSalida1FieldNumber = 4;
    private string horaSalida1_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string HoraSalida1 {
      get { return horaSalida1_; }
      set {
        horaSalida1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Salida2" field.</summary>
    public const int Salida2FieldNumber = 5;
    private string salida2_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Salida2 {
      get { return salida2_; }
      set {
        salida2_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "A_Donde2" field.</summary>
    public const int ADonde2FieldNumber = 6;
    private string aDonde2_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ADonde2 {
      get { return aDonde2_; }
      set {
        aDonde2_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Pista_Salida2" field.</summary>
    public const int PistaSalida2FieldNumber = 7;
    private string pistaSalida2_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PistaSalida2 {
      get { return pistaSalida2_; }
      set {
        pistaSalida2_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Hora_Salida2" field.</summary>
    public const int HoraSalida2FieldNumber = 8;
    private string horaSalida2_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string HoraSalida2 {
      get { return horaSalida2_; }
      set {
        horaSalida2_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Llegda1" field.</summary>
    public const int Llegda1FieldNumber = 9;
    private string llegda1_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Llegda1 {
      get { return llegda1_; }
      set {
        llegda1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "De_donde1" field.</summary>
    public const int DeDonde1FieldNumber = 10;
    private string deDonde1_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DeDonde1 {
      get { return deDonde1_; }
      set {
        deDonde1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Pista_Llegada1" field.</summary>
    public const int PistaLlegada1FieldNumber = 11;
    private string pistaLlegada1_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PistaLlegada1 {
      get { return pistaLlegada1_; }
      set {
        pistaLlegada1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Hora_Llegada1" field.</summary>
    public const int HoraLlegada1FieldNumber = 12;
    private string horaLlegada1_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string HoraLlegada1 {
      get { return horaLlegada1_; }
      set {
        horaLlegada1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Llegda2" field.</summary>
    public const int Llegda2FieldNumber = 13;
    private string llegda2_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Llegda2 {
      get { return llegda2_; }
      set {
        llegda2_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "De_donde2" field.</summary>
    public const int DeDonde2FieldNumber = 14;
    private string deDonde2_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DeDonde2 {
      get { return deDonde2_; }
      set {
        deDonde2_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Pista_Llegada2" field.</summary>
    public const int PistaLlegada2FieldNumber = 15;
    private string pistaLlegada2_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PistaLlegada2 {
      get { return pistaLlegada2_; }
      set {
        pistaLlegada2_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Hora_Llegada2" field.</summary>
    public const int HoraLlegada2FieldNumber = 16;
    private string horaLlegada2_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string HoraLlegada2 {
      get { return horaLlegada2_; }
      set {
        horaLlegada2_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Resp_Pantalla);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Resp_Pantalla other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Salida1 != other.Salida1) return false;
      if (ADonde1 != other.ADonde1) return false;
      if (PistaSalida1 != other.PistaSalida1) return false;
      if (HoraSalida1 != other.HoraSalida1) return false;
      if (Salida2 != other.Salida2) return false;
      if (ADonde2 != other.ADonde2) return false;
      if (PistaSalida2 != other.PistaSalida2) return false;
      if (HoraSalida2 != other.HoraSalida2) return false;
      if (Llegda1 != other.Llegda1) return false;
      if (DeDonde1 != other.DeDonde1) return false;
      if (PistaLlegada1 != other.PistaLlegada1) return false;
      if (HoraLlegada1 != other.HoraLlegada1) return false;
      if (Llegda2 != other.Llegda2) return false;
      if (DeDonde2 != other.DeDonde2) return false;
      if (PistaLlegada2 != other.PistaLlegada2) return false;
      if (HoraLlegada2 != other.HoraLlegada2) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Salida1.Length != 0) hash ^= Salida1.GetHashCode();
      if (ADonde1.Length != 0) hash ^= ADonde1.GetHashCode();
      if (PistaSalida1.Length != 0) hash ^= PistaSalida1.GetHashCode();
      if (HoraSalida1.Length != 0) hash ^= HoraSalida1.GetHashCode();
      if (Salida2.Length != 0) hash ^= Salida2.GetHashCode();
      if (ADonde2.Length != 0) hash ^= ADonde2.GetHashCode();
      if (PistaSalida2.Length != 0) hash ^= PistaSalida2.GetHashCode();
      if (HoraSalida2.Length != 0) hash ^= HoraSalida2.GetHashCode();
      if (Llegda1.Length != 0) hash ^= Llegda1.GetHashCode();
      if (DeDonde1.Length != 0) hash ^= DeDonde1.GetHashCode();
      if (PistaLlegada1.Length != 0) hash ^= PistaLlegada1.GetHashCode();
      if (HoraLlegada1.Length != 0) hash ^= HoraLlegada1.GetHashCode();
      if (Llegda2.Length != 0) hash ^= Llegda2.GetHashCode();
      if (DeDonde2.Length != 0) hash ^= DeDonde2.GetHashCode();
      if (PistaLlegada2.Length != 0) hash ^= PistaLlegada2.GetHashCode();
      if (HoraLlegada2.Length != 0) hash ^= HoraLlegada2.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Salida1.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Salida1);
      }
      if (ADonde1.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ADonde1);
      }
      if (PistaSalida1.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PistaSalida1);
      }
      if (HoraSalida1.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(HoraSalida1);
      }
      if (Salida2.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Salida2);
      }
      if (ADonde2.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ADonde2);
      }
      if (PistaSalida2.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(PistaSalida2);
      }
      if (HoraSalida2.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(HoraSalida2);
      }
      if (Llegda1.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Llegda1);
      }
      if (DeDonde1.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(DeDonde1);
      }
      if (PistaLlegada1.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(PistaLlegada1);
      }
      if (HoraLlegada1.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(HoraLlegada1);
      }
      if (Llegda2.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(Llegda2);
      }
      if (DeDonde2.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(DeDonde2);
      }
      if (PistaLlegada2.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(PistaLlegada2);
      }
      if (HoraLlegada2.Length != 0) {
        output.WriteRawTag(130, 1);
        output.WriteString(HoraLlegada2);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Salida1.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Salida1);
      }
      if (ADonde1.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ADonde1);
      }
      if (PistaSalida1.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PistaSalida1);
      }
      if (HoraSalida1.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(HoraSalida1);
      }
      if (Salida2.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Salida2);
      }
      if (ADonde2.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ADonde2);
      }
      if (PistaSalida2.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PistaSalida2);
      }
      if (HoraSalida2.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(HoraSalida2);
      }
      if (Llegda1.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Llegda1);
      }
      if (DeDonde1.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DeDonde1);
      }
      if (PistaLlegada1.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PistaLlegada1);
      }
      if (HoraLlegada1.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(HoraLlegada1);
      }
      if (Llegda2.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Llegda2);
      }
      if (DeDonde2.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DeDonde2);
      }
      if (PistaLlegada2.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PistaLlegada2);
      }
      if (HoraLlegada2.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(HoraLlegada2);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Resp_Pantalla other) {
      if (other == null) {
        return;
      }
      if (other.Salida1.Length != 0) {
        Salida1 = other.Salida1;
      }
      if (other.ADonde1.Length != 0) {
        ADonde1 = other.ADonde1;
      }
      if (other.PistaSalida1.Length != 0) {
        PistaSalida1 = other.PistaSalida1;
      }
      if (other.HoraSalida1.Length != 0) {
        HoraSalida1 = other.HoraSalida1;
      }
      if (other.Salida2.Length != 0) {
        Salida2 = other.Salida2;
      }
      if (other.ADonde2.Length != 0) {
        ADonde2 = other.ADonde2;
      }
      if (other.PistaSalida2.Length != 0) {
        PistaSalida2 = other.PistaSalida2;
      }
      if (other.HoraSalida2.Length != 0) {
        HoraSalida2 = other.HoraSalida2;
      }
      if (other.Llegda1.Length != 0) {
        Llegda1 = other.Llegda1;
      }
      if (other.DeDonde1.Length != 0) {
        DeDonde1 = other.DeDonde1;
      }
      if (other.PistaLlegada1.Length != 0) {
        PistaLlegada1 = other.PistaLlegada1;
      }
      if (other.HoraLlegada1.Length != 0) {
        HoraLlegada1 = other.HoraLlegada1;
      }
      if (other.Llegda2.Length != 0) {
        Llegda2 = other.Llegda2;
      }
      if (other.DeDonde2.Length != 0) {
        DeDonde2 = other.DeDonde2;
      }
      if (other.PistaLlegada2.Length != 0) {
        PistaLlegada2 = other.PistaLlegada2;
      }
      if (other.HoraLlegada2.Length != 0) {
        HoraLlegada2 = other.HoraLlegada2;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Salida1 = input.ReadString();
            break;
          }
          case 18: {
            ADonde1 = input.ReadString();
            break;
          }
          case 26: {
            PistaSalida1 = input.ReadString();
            break;
          }
          case 34: {
            HoraSalida1 = input.ReadString();
            break;
          }
          case 42: {
            Salida2 = input.ReadString();
            break;
          }
          case 50: {
            ADonde2 = input.ReadString();
            break;
          }
          case 58: {
            PistaSalida2 = input.ReadString();
            break;
          }
          case 66: {
            HoraSalida2 = input.ReadString();
            break;
          }
          case 74: {
            Llegda1 = input.ReadString();
            break;
          }
          case 82: {
            DeDonde1 = input.ReadString();
            break;
          }
          case 90: {
            PistaLlegada1 = input.ReadString();
            break;
          }
          case 98: {
            HoraLlegada1 = input.ReadString();
            break;
          }
          case 106: {
            Llegda2 = input.ReadString();
            break;
          }
          case 114: {
            DeDonde2 = input.ReadString();
            break;
          }
          case 122: {
            PistaLlegada2 = input.ReadString();
            break;
          }
          case 130: {
            HoraLlegada2 = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
