// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Aeropuerto.proto

package proto_to_java.Aeropuerto;

public final class AeropuertoProto {
  private AeropuertoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Aeropuerto_mensaje_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Aeropuerto_mensaje_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Aeropuerto_respuesta_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Aeropuerto_respuesta_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020Aeropuerto.proto\022\nAeropuerto\"\031\n\007mensaj" +
      "e\022\016\n\006altura\030\001 \001(\005\"\031\n\trespuesta\022\014\n\004flag\030\001" +
      " \001(\t2G\n\006Prueba\022=\n\renviar_altura\022\023.Aeropu" +
      "erto.mensaje\032\025.Aeropuerto.respuesta\"\000B3\n" +
      "\030proto_to_java.AeropuertoB\017AeropuertoPro" +
      "toP\001\242\002\003HLWb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Aeropuerto_mensaje_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Aeropuerto_mensaje_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Aeropuerto_mensaje_descriptor,
        new java.lang.String[] { "Altura", });
    internal_static_Aeropuerto_respuesta_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Aeropuerto_respuesta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Aeropuerto_respuesta_descriptor,
        new java.lang.String[] { "Flag", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
