// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Aeropuerto.proto

package proto_to_java.Aeropuerto;

public interface mensajeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Aeropuerto.mensaje)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 altura = 1;</code>
   */
  int getAltura();
}
