// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Aeropuerto.proto

package proto_to_java.Aeropuerto;

public interface respuestaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Aeropuerto.respuesta)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string flag = 1;</code>
   */
  java.lang.String getFlag();
  /**
   * <code>string flag = 1;</code>
   */
  com.google.protobuf.ByteString
      getFlagBytes();
}
