// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Aeropuerto.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Aeropuerto {
  public static partial class Prueba
  {
    static readonly string __ServiceName = "Aeropuerto.Prueba";

    static readonly grpc::Marshaller<global::Aeropuerto.mensaje> __Marshaller_Aeropuerto_mensaje = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Aeropuerto.mensaje.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Aeropuerto.respuesta> __Marshaller_Aeropuerto_respuesta = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Aeropuerto.respuesta.Parser.ParseFrom);

    static readonly grpc::Method<global::Aeropuerto.mensaje, global::Aeropuerto.respuesta> __Method_enviar_altura = new grpc::Method<global::Aeropuerto.mensaje, global::Aeropuerto.respuesta>(
        grpc::MethodType.Unary,
        __ServiceName,
        "enviar_altura",
        __Marshaller_Aeropuerto_mensaje,
        __Marshaller_Aeropuerto_respuesta);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Aeropuerto.AeropuertoReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Prueba</summary>
    public abstract partial class PruebaBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Aeropuerto.respuesta> enviar_altura(global::Aeropuerto.mensaje request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Prueba</summary>
    public partial class PruebaClient : grpc::ClientBase<PruebaClient>
    {
      /// <summary>Creates a new client for Prueba</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PruebaClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Prueba that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PruebaClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PruebaClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PruebaClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Aeropuerto.respuesta enviar_altura(global::Aeropuerto.mensaje request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return enviar_altura(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Aeropuerto.respuesta enviar_altura(global::Aeropuerto.mensaje request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_enviar_altura, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Aeropuerto.respuesta> enviar_alturaAsync(global::Aeropuerto.mensaje request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return enviar_alturaAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Aeropuerto.respuesta> enviar_alturaAsync(global::Aeropuerto.mensaje request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_enviar_altura, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PruebaClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PruebaClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(PruebaBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_enviar_altura, serviceImpl.enviar_altura).Build();
    }

  }
}
#endregion
