# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Torre_pb2 as Torre__pb2


class DespegueStub(object):
  """asignacion pista de despegue

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.enviar_despegue = channel.unary_unary(
        '/Aeropuerto.Despegue/enviar_despegue',
        request_serializer=Torre__pb2.Pista_Des.SerializeToString,
        response_deserializer=Torre__pb2.Resp_Des.FromString,
        )


class DespegueServicer(object):
  """asignacion pista de despegue

  """

  def enviar_despegue(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DespegueServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'enviar_despegue': grpc.unary_unary_rpc_method_handler(
          servicer.enviar_despegue,
          request_deserializer=Torre__pb2.Pista_Des.FromString,
          response_serializer=Torre__pb2.Resp_Des.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Aeropuerto.Despegue', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class AterrizajeStub(object):
  """asignacion pista de aterrizaje
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.enviar_aterrizaje = channel.unary_unary(
        '/Aeropuerto.Aterrizaje/enviar_aterrizaje',
        request_serializer=Torre__pb2.Pista_At.SerializeToString,
        response_deserializer=Torre__pb2.Resp_At.FromString,
        )


class AterrizajeServicer(object):
  """asignacion pista de aterrizaje
  """

  def enviar_aterrizaje(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AterrizajeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'enviar_aterrizaje': grpc.unary_unary_rpc_method_handler(
          servicer.enviar_aterrizaje,
          request_deserializer=Torre__pb2.Pista_At.FromString,
          response_serializer=Torre__pb2.Resp_At.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Aeropuerto.Aterrizaje', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
