# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Torre_pb2 as Torre__pb2


class AeropuertoStub(object):
  """asignacion pista de despegue

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.enviar_despegue = channel.unary_unary(
        '/Aeropuerto.Aeropuerto/enviar_despegue',
        request_serializer=Torre__pb2.Pista_Des.SerializeToString,
        response_deserializer=Torre__pb2.Resp_Des.FromString,
        )
    self.enviar_aterrizaje = channel.unary_unary(
        '/Aeropuerto.Aeropuerto/enviar_aterrizaje',
        request_serializer=Torre__pb2.Pista_At.SerializeToString,
        response_deserializer=Torre__pb2.Resp_At.FromString,
        )
    self.enviar_info = channel.unary_unary(
        '/Aeropuerto.Aeropuerto/enviar_info',
        request_serializer=Torre__pb2.Id_Pantalla.SerializeToString,
        response_deserializer=Torre__pb2.Resp_Pantalla.FromString,
        )


class AeropuertoServicer(object):
  """asignacion pista de despegue

  """

  def enviar_despegue(self, request, context):
    """solicitud de despegue
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def enviar_aterrizaje(self, request, context):
    """asignacion pista de aterrizaje
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def enviar_info(self, request, context):
    """Enviar info pantallas
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AeropuertoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'enviar_despegue': grpc.unary_unary_rpc_method_handler(
          servicer.enviar_despegue,
          request_deserializer=Torre__pb2.Pista_Des.FromString,
          response_serializer=Torre__pb2.Resp_Des.SerializeToString,
      ),
      'enviar_aterrizaje': grpc.unary_unary_rpc_method_handler(
          servicer.enviar_aterrizaje,
          request_deserializer=Torre__pb2.Pista_At.FromString,
          response_serializer=Torre__pb2.Resp_At.SerializeToString,
      ),
      'enviar_info': grpc.unary_unary_rpc_method_handler(
          servicer.enviar_info,
          request_deserializer=Torre__pb2.Id_Pantalla.FromString,
          response_serializer=Torre__pb2.Resp_Pantalla.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Aeropuerto.Aeropuerto', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
